### ISSUE TITLE
How does this work???

### ISSUE THREAD

**Issue by jafioti** [martindevans/hypernonsense#4]
I'm trying to follow your documentation, which uses a function internal to your own crate. Why??? 

It also uses an old version of rand which you don't specify anywhere. 

Even if all of that works, the example still doesn't work because the group() function takes in a BitVec, not a Vec<f64>, so I don't know what you were smoking when you made this awful example code. 

I now have no idea how to use this because I don't know how to convert a Vec<f64> to a BitVec.

**Comment by martindevans** [comment]
It's been a long time since I worked on this, so some of the details are a bit fuzzy!

> uses a function internal to your own crate. Why???

Probably an oversite, which function?

> It also uses an old version of rand which you don't specify anywhere.

All the dependencies, including the version of `rand` in use, as specified in [cargo.toml](https://github.com/martindevans/hypernonsense/blob/master/Cargo.toml#L17). Same as any other Rust project.

> the group() function takes in a BitVec

You can convert a vector into a BitVec using the [`key`](https://github.com/martindevans/hypernonsense/blob/master/src/hyperindex.rs#L42) function on the hyperindex. The BitVec specifies which group in the hyperindex the vector is in.

> I don't know what you were smoking when you made this awful example code.

Don't be unpleasant to people helping you out for free.

**Comment by jafioti** [comment]
> Don't be unpleasant to people helping you out for free.

Sorry I was a bit heated when I wrote that, you're right.

> Probably an oversite, which function?

random_unit_vector(), distance(), get_vector_by_key(). I don't know what the last two do because they aren't in the crate.



> All the dependencies, including the version of `rand` in use, as specified in [cargo.toml](https://github.com/martindevans/hypernonsense/blob/master/Cargo.toml#L17). Same as any other Rust project.

I was confused because I need to also use that old version of rand in my code, not just that you use it internally, but the end user is required to change that in their code. Just a comment about that would be helpful.

Again, sorry for the angry tone of my comment, thanks for the response.

**Comment by martindevans** [comment]
Those three functions are just for demo purposes:

> random_unit_vector()

This just generates a random vector with length `1.0`. In real use you'd want to be passing in vectors that actually mean something.

> distance()

You can define your own distance function, this is just a stand-in for whatever distance func you're using. Usually cosine distance is what you want, so it would probably be worth making the [`modified_cosine_distance`](https://github.com/martindevans/hypernonsense/blob/master/src/vector.rs#L15) method available.

> get_vector_by_key()

When you insert something into the index you supply a key and a vector. This function takes the key and must provide the same vector again. Again, this is really up to you. In my usage of this library I just store the `Key->Vector` lookup in a `HashMap`, but you could also use a database if you wanted to save memory for example.

> I need to also use that old version of rand in my code

Well, it's wasn't an old version when I wrote this 😆 

It could probably be updated fairly easily, if you want to submit a PR for it I'll publish an updated crate with that changed.
